### ISSUE TITLE
typedoc warning "TypeDoc has been loaded multiple times. This is commonly caused by plugins which have their own installation of TypeDoc."

### ISSUE THREAD

**Issue by jklosinski** [ferdodo/typedoc-plugin-include-example#10]
I have a project which has typedoc and this plugin installed directly.  When I run typedoc, it fails with the following warning (I have `treatWarningsAsErrors` enabled): 

```
TypeDoc has been loaded multiple times. This is commonly caused by plugins which have their own installation of TypeDoc.
        <...>\api\node_modules\typedoc
        <...>\api\node_modules\typedoc-plugin-include-example\node_modules\typedoc
```

When I look at the plugin's node_modules folder, typedoc is indeed there.  Is this expected?

For reference, here is my package.json:
```json
"devDependencies": {
  "typedoc": "^0.26.11",
  "typedoc-plugin-include-example": "^1.4.1",
  "typescript": "5.6"
}
```

**Comment by ferdodo** [comment]
It seems to be solved now. I removed the npm-shrinkwrap.json entirely from publication, I think it was causing the dependency duplication, even if typedoc isn't even listed in the shrinkwrap itself. I'll take some time in the next publication to confirm this was the cause.

I also have one of my own project to build with --treatWarningsAsErrors, so I can catch if anything is wrong in the future.
