### ISSUE TITLE
[Feature] "End" Line Selector

### ISSUE THREAD

**Issue by spenpal** [ferdodo/typedoc-plugin-include-example#8]
Currently, line selectors need a start and end line number to work.

```
/**
 * @includeExample path/to/your/example.ts:1-5,10
 */
function myFunction() {
    // ...
}
```

However, it would be much easier to have an end-line selector that ends at the end of the file.

For example, the example below will only selects lines starting from 2 to the end of the file. This makes it easier on the dev to maintain these Typedocs, as the file they are referring might expand in the future, but they still want to exclude a beginning few lines, for whatever reason.

```
/**
 * @includeExample path/to/your/example.ts:2-
 */
function myFunction() {
    // ...
}
```

**Comment by ferdodo** [comment]
Good idea, I didn't find an official notation for selecting lines in a file, but it does look like the good way. You can implement it, or I'll do it in an upcoming version.

**Comment by spenpal** [comment]
I've never contributed to open source before, but I would love to give it a shot!

You mentioning about an official notation got me thinking about a more expressive "line selection" syntax.

Please see #9 for my thoughts on this!
